name: build-and-sync

on:
  schedule:
    - cron: '0 0 * * *' # Todo dia à meia-noite
  workflow_dispatch: # Botão manual

jobs:
  update-feed:
    uses: pepa667/insta-scraper/.github/workflows/scrape-reusable.yml@main
    secrets:
      SCRAPER_API_KEY: ${{ secrets.SCRAPER_API_KEY }}
      INSTA_USERNAME: ${{ secrets.INSTA_USERNAME }}
      INSTA_SESSION_ID: ${{ secrets.INSTA_SESSION_ID }}